### ISSUE TITLE
Sanitize names when copying a data.frame?

### ISSUE THREAD

**Issue by dmbates** [JuliaInterop/RCall.jl#112]
I find myself needing to use

```
@rget foo
names!(foo, [Symbol(replace(string(nm), '.', '_')) for nm in names(foo)]
```

on many of the R data frames that I load.  Would it be worthwhile adding an optional argument somewhere along the line to rewrite the names?

**Comment by randy3k** [comment]
The same applies to R list `rcopy("list(a.b=1)")`. And similar issues appear when importing a R library.

```julia
julia> @rimport MASS

julia> names(MASS)
166-element Array{Symbol,1}:          
 ⋮                        
 symbol("write.matrix")
 :wtloss    
```
For instance, `write.matrix` cannot be easier extracted. Resolving the issue in this case is a little bit tricky since it is more likely to have variable name collision within a module than within a list or a data frame.

**Comment by nalimilan** [comment]
Looks like that indeed would be a nice default behavior.
