### ISSUE TITLE
Julia exits abruptly if we do "using RCall" on Windows

### ISSUE THREAD

**Issue by bmharsha** [JuliaInterop/RCall.jl#170]
Julia doesn't gives any error message while exiting (I started Julia from command prompt).
```
julia> using RCall
INFO: Precompiling module RCall.
INFO: Using R installation at C:/Program Files/Microsoft/R Server/R_SERVER

C:\Users\Username\AppData\Local\Julia-0.5.1\bin>
```

Following lines give information on the environment where I tried to import RCall.jl (This is a DSVM, Data Science Virtual Machine )

* OS = Windows Server 2012 R2 Datacenter 
* Microsoft R Open 3.3.2
*  Microsoft R Server packages, version 9.0.1
* RStudio = Version 1.0.44 
* RCall.jl version = 0.6.4
* Julia version = tried on both v0.5.0 and v0.5.1
* R_HOME environment variable was pointing to `"C:/Program Files/Microsoft/R Server/R_SERVER"`

Previously I had tested with Microsoft R Open v3.3.1 on the same platform,  RCall.jl was working fine, even `Pkg.test("RCall")` was going through.

**Comment by simonbyrne** [comment]
It loads correctly if I comment out the call to `R_SetParams` (which is used for capturing the output). Not sure why.

**Comment by DvP17** [comment]
I have the same Problem. Julia exits when I am trying to "using RCall"

Before this, I had a Problem with Microsoft R Client. I have uninstalled it, since an error came up mentioning that R < 3.4 is not supported and installed it again (Windows 8.1). Everything worked, no error message showed up. However, Julia exits when I try to use RCall. When doing Pkg.test("RCall") I get the following error message:
![error_using_rcall](https://user-images.githubusercontent.com/26024076/46910444-98052580-cf44-11e8-827c-677342c95b3c.PNG)

@simonbyrne How do I do this exactly?
