### ISSUE TITLE
Errors in R when using RCall and JuliaCall cause segfaults with RCall v0.8.0

### ISSUE THREAD

**Issue by Non-Contradiction** [JuliaInterop/RCall.jl#215]
When developing JuliaCall, I found some issues when using RCall and JuliaCall at the same time. Following is the code and its behaviour with RCall v0.7.5
```
library(JuliaCall)
julia_setup()
julia_eval('R"dontexist"')
## Error: Unable to find object  'dontexist'
## Error: Error happens in Julia.
```
When using RCall v0.8.0, the same code will cause segfault. I see the error handling method in RCall has changed and wonder whether it is the root of the issue.

**Comment by Non-Contradiction** [comment]
The code is okay to be run from Julia by using RCall, both with 0.7.5 and 0.8.0
```
using RCall
R"library(JuliaCall)"
R"julia_setup()"
R"julia_eval('R\"dontexist\"')"
```
but run from R is problematic with RCall 0.8.0

Also, using `git bisect`, this issue occurs from the [[8f69d82] a major refactoring of io code](https://github.com/JuliaInterop/RCall.jl/commit/8f69d824ae1d81438369a5eda97aa0ad296892c7)

**Comment by randy3k** [comment]
It should be fixed at 3cbc3fe.

This line was removed from the codebase because I thought that only repl mode requires it and the repl code has been refactored and doesn't need this. I didn't realize that JuliaCall would not redirect the stdout and stderr so we need to throw an error explicitly when the evaluation was failed.

**Comment by randy3k** [comment]
Let me know if it works :).

**Comment by Non-Contradiction** [comment]
It works! Thank you very much.
