### ISSUE TITLE
How to install R packages though RCall.jl

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaInterop/RCall.jl#420]
Hey folks, I don't know if I missed it in the docs but I did not see how to install a R package through Rcall. I posted a SO question here: https://stackoverflow.com/questions/68048899/how-to-install-an-r-package-using-rcall-jl

**Comment by TheCedarPrince** [comment]
Also, @logankilpatrick if you run into problems, you could exit the RCall environment and open your R version and install packages directly inside of the native R REPL and then jump back into RCall mode. I've also found using renv helps preserve the package versions and needed packages properly.

**Comment by pat-alt** [comment]
I'm having a related issue and thought I'd revive this existing thread, instead of opening a new one. 

I can see how this all works out really nicely when working locally (fantastic package by the way). But what if I want to use RCall as a dependency of my own Julia package? Is there an elegant/preferred way of making sure that R package deps are installed (ideally upon load)?

Have posted a more detail question on [discourse](https://discourse.julialang.org/t/rcall-jl-how-to-handle-r-package-dependencies/83172), but thought it's worth going straight to the source 😄.

Thanks!

**Comment by palday** [comment]
for posterity:

```julia
using RCall
reval("""install.packages(c("pkg1", "pkg2"))"""
```

**Comment by palday** [comment]
oh and @pat-alt 

```julia
reval("""if(!require("mypkg")){
install.packages("mypkg")
library("mypkg")
}
"""

`require` returns a boolean about whether a package was successfully loaded, while `library` errors if the package can't be loaded.
