### ISSUE TITLE
Proper Way to Load Libraries in .Rprofile

### ISSUE THREAD

**Issue by nateybear** [JuliaInterop/RCall.jl#446]
I'm raising this issue to ask for advice on library loading when the RCall session starts up. I have a .Rprofile in my working directory like this:
```R
print("inside of R profile")
require(tidyverse)
```
I would expect the `tidyverse` library to be loaded and available in my REPL, however I get an error:
<img width="513" alt="Screen Shot 2022-02-20 at 3 37 43 PM" src="https://user-images.githubusercontent.com/9449706/154865387-82fd4dfd-92f8-41ef-a663-dbba35d96bbd.png">
I like to load a "base" set of R libraries in my .Rprofile for when my R session starts up, and the behavior of RCall does not line up in this sense with my typical R workflow.

Any advice on loading libraries in a startup script is appreciated!

**Comment by simonbyrne** [comment]
What OS are you on?

**Comment by nateybear** [comment]
macOS Big Sur (11.6.1), I'm running Julia 1.6.3 and R 4.0.2

**Comment by palday** [comment]
My recommendation is to use `library` instead of `require` to throw an effort when package loading fails. Alternatively, check the return value of `require`. My strong suspicion is that something is going wrong in loading tidyverse and hence magittr (which is where the pipe operator `%>%` is actually defined).
